version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.1
    working_directory: ~/EliteDangerous-UDP-Dispatcher
    steps:
      - checkout
      - run:
        name: Restore packages
        command: dotnet Restore

      - run:
        name: Build solution
        command: dotnet build -c Release