version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.1
    working_directory: ~/EliteDangerous-UDP-Dispatcher
    steps:
      - checkout
      - run: dotnet Restore
      - run: dotnet build -c Release